---
- hosts: all
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: installed
    - name: configure
      shell: "echo Hello Natwest guys , Vijay Anandh Kesavan this side over the Web !! > /var/www/html/index.html"
    - name: start service
      service:
        name: httpd
        state: started
    - name: add user
      user:
        name: raman
        state: absent
